"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.listaDeJogadores = void 0;
exports.listaDeJogadores = [
    {
        nome: "L. Messi",
        overal: 93,
        posicao: "PD|ATA|SA",
        idade: 34,
        imagem: "https://cdn.sofifa.net/players/158/023/22_120.png",
        pernaBoa: "esq",
        finta: "fnt",
        pernaRuim: "pr",
        fintaStar: 4,
        prStar: 4,
        valorDeMercado: 78
    },
    {
        nome: "	R. Lewandowski",
        overal: 92,
        posicao: "ATA",
        idade: 29,
        imagem: "https://cdn.sofifa.net/players/188/545/22_120.png",
        pernaBoa: "dir",
        finta: "fnt",
        pernaRuim: "pr",
        fintaStar: 4,
        prStar: 4,
        valorDeMercado: 119.5
    },
    {
        nome: "Neymar",
        overal: 91,
        posicao: "PE | MEI",
        idade: 29,
        imagem: "https://cdn.sofifa.net/players/190/871/22_120.png",
        pernaBoa: "dir",
        finta: "fnt",
        pernaRuim: "pr",
        fintaStar: 5,
        prStar: 5,
        valorDeMercado: 85.5
    },
    {
        nome: "K. Mbappé",
        overal: 91,
        posicao: "ATA|PE",
        idade: 22,
        imagem: "https://cdn.sofifa.net/players/231/747/22_120.png",
        pernaBoa: "dir",
        finta: "fnt",
        pernaRuim: "pr",
        fintaStar: 5,
        prStar: 4,
        valorDeMercado: 194
    },
    {
        nome: "K. Benzema",
        overal: 91,
        posicao: "PD",
        idade: 33,
        imagem: "https://cdn.sofifa.net/players/165/153/22_120.png",
        pernaBoa: "dir",
        finta: "fnt",
        pernaRuim: "pr",
        fintaStar: 4,
        prStar: 4,
        valorDeMercado: 84
    },
    {
        nome: "M. Salah",
        overal: 91,
        posicao: "PD",
        idade: 22,
        imagem: "https://cdn.sofifa.net/players/209/331/22_120.png",
        pernaBoa: "esq",
        finta: "fnt",
        pernaRuim: "pr",
        fintaStar: 4,
        prStar: 3,
        valorDeMercado: 129
    },
    {
        nome: "	Zlatan Ibrahimović",
        overal: 83,
        posicao: "ATA",
        idade: 39,
        imagem: "https://cdn.sofifa.net/players/041/236/22_120.png",
        pernaBoa: "dir",
        finta: "fnt",
        pernaRuim: "pr",
        fintaStar: 5,
        prStar: 4,
        valorDeMercado: 12.5
    },
    {
        nome: "	Marko Arnautović",
        overal: 81,
        posicao: "ATA",
        idade: 31,
        imagem: "https://cdn.sofifa.net/players/184/200/21_120.png",
        pernaBoa: "dir",
        finta: "fnt",
        pernaRuim: "pr",
        fintaStar: 4,
        prStar: 4,
        valorDeMercado: 12
    },
    {
        nome: "M. Salah",
        overal: 91,
        posicao: "PD",
        idade: 22,
        imagem: "https://cdn.sofifa.net/players/209/331/22_120.png",
        pernaBoa: "esq",
        finta: "fnt",
        pernaRuim: "pr",
        fintaStar: 4,
        prStar: 3,
        valorDeMercado: 129
    },
];
